### ISSUE TITLE
Add a small number of standardized fields to the study descriptions?

### ISSUE THREAD

**Issue by mhebing** [ddionrails/study-catalogue#1]
Standardized fields might be helpful to integrate the study descriptions in the search index.

Preliminary list:

* year of the first wave
* frequency of iterations
* geographical coverage
* sample size
* main topics
* (primary) analysis units
* survey modes

@jgoebel @kwenzig Thoughts on that?

**Comment by kwenzig** [comment]
* label (multilingual)
* description (multilingual)

remember: there can be multiple samples, perhaps some of the information should "belong" to "sample"
